version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "11:00"
    timezone: America/Los_Angeles
  ignore:
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: netlify-cms-app
    versions:
    - 2.14.32
    - 2.14.35
    - 2.14.40
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
    - 7.23.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.3
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.12.1
  - dependency-name: start-server-and-test
    versions:
    - 1.12.1
  - dependency-name: gatsby-plugin-netlify
    versions:
    - 2.11.1
  - dependency-name: gatsby-image
    versions:
    - 3.0.0
    - 3.1.0
  - dependency-name: cypress
    versions:
    - 6.6.0
    - 6.8.0
  - dependency-name: gatsby-cli
    versions:
    - 3.0.0
    - 3.1.0
  - dependency-name: gatsby
    versions:
    - 2.32.11
    - 2.32.9
