version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
  test-e2e:
    docker:
      - image: cypress/included:3.5.0
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:e2e:ci
