version: 2

workflows:
  version: 2
  all:
    jobs:
      - test-e2e

jobs:
  test-e2e:
    docker:
      - image: cypress/included:3.5.0
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:e2e:ci
