backend:
  name: test-repo
  # name: github
  # repo: lynncyrin/lynncyrin-dot-me

media_folder: static/img
public_folder: /images

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "template-key", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      #  Removing Featuring options as this is a personal blog not a Professional blog or article site
      # - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      # - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      # I still need to integrate Tags
      # - {label: "Tags", name: "tags", widget: "list"}
