name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    # https://github.com/actions/runner-images
    runs-on: ubuntu-22.04
    # https://hub.docker.com/_/node/
    container: node:16
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: npm run test:quick
      - run: npm run test:e2e:ci
